DROP TABLE IF EXISTS PERSON;
CREATE TABLE PERSON (
                        ID   IDENTITY NOT NULL PRIMARY KEY,
                        NAME VARCHAR NOT NULL,
                        FIRSTNAME VARCHAR NOT NULL
);

INSERT INTO PERSON(NAME, FIRSTNAME) VALUES ('Durand', 'Pierre');
INSERT INTO PERSON(NAME, FIRSTNAME) VALUES ('Dupont', 'Marie');
INSERT INTO PERSON(NAME, FIRSTNAME) VALUES ('Dupont', 'Jacques');